services:
  postgres:
    image: postgres:17.4
    container_name: series-tracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./.docker/redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

